### ISSUE TITLE
Refactor the Stubs so it uses the module pattern

### ISSUE THREAD

**Issue by jamesmortensen** [jamesmortensen/node-webkit-chrome-api-stubs#2]
Currently, the stubs are represented by one really huge JavaScript object literal.  Instead, using something like the module or even the constructor pattern will let us wrap more complex, stateful API's without leaking variables into the global context.

**Comment by telecran-telecrit** [comment]
It is not required. You can wait more than 8 years, because of no time to support latest js features. 

More important is just gereric stubs patch for NWjs (node-webkit).
